base_image: "anyscale/ray-ml:pinned-nightly-py37-gpu"
env_vars: { }
debian_packages:
  - curl

python:
  pip_packages:
    - pytest
    - torch
    - torchvision
    - fastapi
    - uvicorn
    - tblib
    - filelock>=3.3.0
  conda_packages: [ ]

post_build_cmds:
  - pip uninstall -y ray || true
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
  - wget -qO- https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-359.0.0-linux-x86_64.tar.gz | tar xvz
  - sudo ln -s $(pwd)/google-cloud-sdk/bin/gsutil /usr/bin/gsutil
